# Copyright (c) Edward A. Roualdes, 2019.
# Distributed under the terms of the Modified BSD License.
---

version: '3'
services:
  nginx:
    build:
      context: ./nginx
      args:
        - icc=false
        - security-opt=no-new-privileges
    links:
      - web
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure:5
  kernel_gateway:
    build:
      context: ./kernel
    ports:
      - "8888:8888" # for testing direct access to the kernel gateway from outside docker
    image: jupyter/kernel-gateway
    environment:
      KG_ALLOW_ORIGIN: '*'
  web:
    build:
      context: ./app
      args:
        - icc=false
        - security-opt=no-new-privileges
    environment:
      - DEVELOPMENT=true
      - BASE_GATEWAY_HTTP_URL=http://nginx/jupyter/v1/12345678-1234-1234-1234-123456789012
      # see https://github.com/jupyter/jupyter-js-services/issues/158 about username/password here
      - BASE_GATEWAY_WS_URL=ws://fakeuser:fakepass@nginx/jupyter/v1/12345678-1234-1234-1234-123456789012
      - BASE_GATEWAY_USERNAME=fakeuser
      - BASE_GATEWAY_PASSWORD=fakepass
    restart: on-failure:5
